# Generated by Django 5.1.5 on 2025-01-24 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm_app', '0002_lead'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lead',
            name='contact_email',
        ),
        migrations.RemoveField(
            model_name='lead',
            name='phone_number',
        ),
        migrations.RemoveField(
            model_name='lead',
            name='restaurant_name',
        ),
        migrations.RemoveField(
            model_name='lead',
            name='status',
        ),
        migrations.AddField(
            model_name='lead',
            name='annual_revenue',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='city',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='company',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='country',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='email_opt_out',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='lead',
            name='fax',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='first_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='industry',
            field=models.CharField(choices=[('NONE', '-None-'), ('ASP', 'ASP (Application Service Provider)'), ('DATA_TELECOM_OEM', 'Data/Telecom OEM'), ('ERP', 'ERP (Enterprise Resource Planning)'), ('GOVERNMENT_MILITARY', 'Government/Military'), ('LARGE_ENTERPRISE', 'Large Enterprise'), ('MANAGEMENT_ISV', 'Management ISV'), ('MSP', 'MSP (Management Service Provider)'), ('NETWORK_EQUIPMENT_ENTERPRISE', 'Network Equipment Enterprise'), ('NON_MANAGEMENT_ISV', 'Non-management ISV'), ('OPTICAL_NETWORKING', 'Optical Networking'), ('SERVICE_PROVIDER', 'Service Provider'), ('SMALL_MEDIUM_ENTERPRISE', 'Small/Medium Enterprise'), ('STORAGE_EQUIPMENT', 'Storage Equipment'), ('STORAGE_SERVICE_PROVIDER', 'Storage Service Provider'), ('SYSTEMS_INTEGRATOR', 'Systems Integrator'), ('WIRELESS_INDUSTRY', 'Wireless Industry')], default='NONE', max_length=50),
        ),
        migrations.AddField(
            model_name='lead',
            name='last_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='lead_source',
            field=models.CharField(choices=[('NONE', '-None-'), ('ADVERTISEMENT', 'Advertisement'), ('COLD_CALL', 'Cold Call'), ('EMPLOYEE_REFERRAL', 'Employee Referral'), ('EXTERNAL_REFERRAL', 'External Referral'), ('ONLINE_STORE', 'Online Store'), ('PARTNER', 'Partner'), ('PUBLIC_RELATIONS', 'Public Relations'), ('SALES_EMAIL_ALIAS', 'Sales Email Alias'), ('SEMINAR_PARTNER', 'Seminar Partner'), ('INTERNAL_SEMINAR', 'Internal Seminar'), ('TRADE_SHOW', 'Trade Show'), ('WEB_DOWNLOAD', 'Web Download'), ('WEB_RESEARCH', 'Web Research'), ('CHAT', 'Chat'), ('TWITTER', 'X (Twitter)'), ('FACEBOOK', 'Facebook')], default='NONE', max_length=50),
        ),
        migrations.AddField(
            model_name='lead',
            name='lead_status',
            field=models.CharField(choices=[('NONE', '-None-'), ('ATTEMPTED_CONTACT', 'Attempted to Contact'), ('CONTACT_IN_FUTURE', 'Contact in Future'), ('CONTACTED', 'Contacted'), ('JUNK_LEAD', 'Junk Lead'), ('LOST_LEAD', 'Lost Lead'), ('NOT_CONTACTED', 'Not Contacted'), ('PRE_QUALIFIED', 'Pre-Qualified'), ('NOT_QUALIFIED', 'Not Qualified')], default='NONE', max_length=50),
        ),
        migrations.AddField(
            model_name='lead',
            name='mobile',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='no_of_employees',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='rating',
            field=models.CharField(choices=[('NONE', '-None-'), ('ACQUIRED', 'Acquired'), ('ACTIVE', 'Active'), ('MARKET_FAILED', 'Market Failed'), ('PROJECT_CANCELLED', 'Project Cancelled'), ('SHUT_DOWN', 'Shut Down')], default='NONE', max_length=50),
        ),
        migrations.AddField(
            model_name='lead',
            name='secondary_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='skype_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='state',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='street',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='twitter',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='website',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='zip_code',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='lead',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
